// Lightweight location data - only major cities and states
export const MAJOR_CITIES = [
  'Mumbai', 'New Delhi', 'Bengaluru', 'Hyderabad', 'Chennai',
  'Pune', 'Ahmedabad', 'Kolkata', 'Jaipur', 'Surat',
  'Lucknow', 'Chandigarh', 'Indore', 'Kochi', 'Guwahati',
  'Bhopal', 'Bhubaneswar', 'Ranchi', 'Patna', 'Visakhapatnam'
];

export const INDIAN_STATES = [
  { name: 'Andaman & Nicobar Islands', code: 'AN' },
  { name: 'Andhra Pradesh', code: 'AP' },
  { name: 'Arunachal Pradesh', code: 'AR' },
  { name: 'Assam', code: 'AS' },
  { name: 'Bihar', code: 'BR' },
  { name: 'Chandigarh', code: 'CH' },
  { name: 'Chhattisgarh', code: 'CG' },
  { name: 'Dadra & Nagar Haveli and Daman & Diu', code: 'DD' },
  { name: 'Delhi', code: 'DL' },
  { name: 'Goa', code: 'GA' },
  { name: 'Gujarat', code: 'GJ' },
  { name: 'Haryana', code: 'HR' },
  { name: 'Himachal Pradesh', code: 'HP' },
  { name: 'Jammu & Kashmir', code: 'JK' },
  { name: 'Jharkhand', code: 'JH' },
  { name: 'Karnataka', code: 'KA' },
  { name: 'Kerala', code: 'KL' },
  { name: 'Ladakh', code: 'LA' },
  { name: 'Lakshadweep', code: 'LD' },
  { name: 'Madhya Pradesh', code: 'MP' },
  { name: 'Maharashtra', code: 'MH' },
  { name: 'Manipur', code: 'MN' },
  { name: 'Meghalaya', code: 'ML' },
  { name: 'Mizoram', code: 'MZ' },
  { name: 'Nagaland', code: 'NL' },
  { name: 'Odisha', code: 'OR' },
  { name: 'Puducherry', code: 'PY' },
  { name: 'Punjab', code: 'PB' },
  { name: 'Rajasthan', code: 'RJ' },
  { name: 'Sikkim', code: 'SK' },
  { name: 'Tamil Nadu', code: 'TN' },
  { name: 'Telangana', code: 'TS' },
  { name: 'Tripura', code: 'TR' },
  { name: 'Uttar Pradesh', code: 'UP' },
  { name: 'Uttarakhand', code: 'UK' },
  { name: 'West Bengal', code: 'WB' }
];

export const CITIES_BY_STATE: Record<string, string[]> = {
  AN: ['Port Blair'],
  AP: ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Tirupati'],
  AR: ['Itanagar'],
  AS: ['Guwahati', 'Dibrugarh', 'Silchar'],
  BR: ['Patna', 'Gaya', 'Muzaffarpur'],
  CH: ['Chandigarh'],
  CG: ['Raipur', 'Bhilai', 'Bilaspur'],
  DD: ['Daman', 'Diu', 'Silvassa'],
  DL: ['New Delhi'],
  GA: ['Panaji', 'Margao'],
  GJ: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot'],
  HR: ['Gurugram', 'Faridabad', 'Panipat'],
  HP: ['Shimla', 'Manali', 'Dharamshala'],
  JK: ['Srinagar', 'Jammu'],
  JH: ['Ranchi', 'Jamshedpur', 'Dhanbad'],
  KA: ['Bengaluru', 'Mysuru', 'Mangaluru', 'Hubballi'],
  KL: ['Kochi', 'Thiruvananthapuram', 'Kozhikode'],
  LA: ['Leh', 'Kargil'],
  LD: ['Kavaratti'],
  MP: ['Indore', 'Bhopal', 'Jabalpur', 'Gwalior'],
  MH: ['Mumbai', 'Pune', 'Nagpur', 'Nashik'],
  MN: ['Imphal'],
  ML: ['Shillong'],
  MZ: ['Aizawl'],
  NL: ['Kohima', 'Dimapur'],
  OR: ['Bhubaneswar', 'Cuttack', 'Rourkela'],
  PY: ['Puducherry', 'Karaikal'],
  PB: ['Ludhiana', 'Amritsar', 'Jalandhar'],
  RJ: ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota'],
  SK: ['Gangtok'],
  TN: ['Chennai', 'Coimbatore', 'Madurai', 'Salem'],
  TS: ['Hyderabad', 'Warangal', 'Nizamabad'],
  TR: ['Agartala'],
  UP: ['Lucknow', 'Kanpur', 'Noida', 'Varanasi'],
  UK: ['Dehradun', 'Haridwar', 'Nainital'],
  WB: ['Kolkata', 'Howrah', 'Siliguri']
};

export const CITY_COORDINATES: Record<string, { lat: number; lng: number }> = {
  Mumbai: { lat: 19.0760, lng: 72.8777 },
  'New Delhi': { lat: 28.6139, lng: 77.2090 },
  Bengaluru: { lat: 12.9716, lng: 77.5946 },
  Hyderabad: { lat: 17.3850, lng: 78.4867 },
  Chennai: { lat: 13.0827, lng: 80.2707 },
  Pune: { lat: 18.5204, lng: 73.8567 },
  Ahmedabad: { lat: 23.0225, lng: 72.5714 },
  Kolkata: { lat: 22.5726, lng: 88.3639 },
  Jaipur: { lat: 26.9124, lng: 75.7873 },
  Surat: { lat: 21.1702, lng: 72.8311 },
  Lucknow: { lat: 26.8467, lng: 80.9462 },
  Chandigarh: { lat: 30.7333, lng: 76.7794 },
  Indore: { lat: 22.7196, lng: 75.8577 },
  Kochi: { lat: 9.9312, lng: 76.2673 },
  Guwahati: { lat: 26.1445, lng: 91.7362 },
  Bhopal: { lat: 23.2599, lng: 77.4126 },
  Bhubaneswar: { lat: 20.2961, lng: 85.8245 },
  Ranchi: { lat: 23.3441, lng: 85.3096 },
  Patna: { lat: 25.5941, lng: 85.1376 },
  Visakhapatnam: { lat: 17.6868, lng: 83.2185 }
};
