// Lightweight location data - only major cities and states
export const MAJOR_CITIES = [
  'Mumbai', 'New Delhi', 'Bengaluru', 'Hyderabad', 'Chennai',
  'Pune', 'Ahmedabad', 'Kolkata', 'Jaipur', 'Surat',
  'Lucknow', 'Chandigarh', 'Indore', 'Kochi', 'Guwahati',
  'Bhopal', 'Bhubaneswar', 'Ranchi', 'Patna', 'Visakhapatnam'
];

export const INDIAN_STATES = [
  { name: 'Andaman & Nicobar Islands', code: 'AN' },
  { name: 'Andhra Pradesh', code: 'AP' },
  { name: 'Arunachal Pradesh', code: 'AR' },
  { name: 'Assam', code: 'AS' },
  { name: 'Bihar', code: 'BR' },
  { name: 'Chandigarh', code: 'CH' },
  { name: 'Chhattisgarh', code: 'CG' },
  { name: 'Dadra & Nagar Haveli and Daman & Diu', code: 'DD' },
  { name: 'Delhi', code: 'DL' },
  { name: 'Goa', code: 'GA' },
  { name: 'Gujarat', code: 'GJ' },
  { name: 'Haryana', code: 'HR' },
  { name: 'Himachal Pradesh', code: 'HP' },
  { name: 'Jammu & Kashmir', code: 'JK' },
  { name: 'Jharkhand', code: 'JH' },
  { name: 'Karnataka', code: 'KA' },
  { name: 'Kerala', code: 'KL' },
  { name: 'Ladakh', code: 'LA' },
  { name: 'Lakshadweep', code: 'LD' },
  { name: 'Madhya Pradesh', code: 'MP' },
  { name: 'Maharashtra', code: 'MH' },
  { name: 'Manipur', code: 'MN' },
  { name: 'Meghalaya', code: 'ML' },
  { name: 'Mizoram', code: 'MZ' },
  { name: 'Nagaland', code: 'NL' },
  { name: 'Odisha', code: 'OR' },
  { name: 'Puducherry', code: 'PY' },
  { name: 'Punjab', code: 'PB' },
  { name: 'Rajasthan', code: 'RJ' },
  { name: 'Sikkim', code: 'SK' },
  { name: 'Tamil Nadu', code: 'TN' },
  { name: 'Telangana', code: 'TS' },
  { name: 'Tripura', code: 'TR' },
  { name: 'Uttar Pradesh', code: 'UP' },
  { name: 'Uttarakhand', code: 'UK' },
  { name: 'West Bengal', code: 'WB' }
];

/** Major cities / district towns per state & UT for filters and location picker (pan-India coverage). */
export const CITIES_BY_STATE: Record<string, string[]> = {
  AN: ['Port Blair', 'Diglipur', 'Mayabunder', 'Rangat', 'Car Nicobar'],
  AP: [
    'Visakhapatnam', 'Vijayawada', 'Guntur', 'Tirupati', 'Nellore', 'Kurnool', 'Rajahmundry', 'Kakinada',
    'Kadapa', 'Anantapur', 'Ongole', 'Eluru', 'Machilipatnam', 'Vizianagaram', 'Srikakulam', 'Chittoor',
    'Tenali', 'Proddatur', 'Hindupur', 'Bhimavaram', 'Madanapalle', 'Gudivada', 'Nandyal', 'Tadepalligudem',
    'Amaravati', 'Tadipatri', 'Chilakaluripet',
  ],
  AR: ['Itanagar', 'Naharlagun', 'Pasighat', 'Tawang', 'Ziro', 'Bomdila', 'Tezu', 'Along'],
  AS: [
    'Guwahati', 'Dibrugarh', 'Silchar', 'Jorhat', 'Nagaon', 'Tinsukia', 'Tezpur', 'Bongaigaon', 'Dhubri',
    'Goalpara', 'North Lakhimpur', 'Sivasagar', 'Karimganj', 'Hailakandi', 'Golaghat', 'Barpeta',
  ],
  BR: [
    'Patna', 'Gaya', 'Muzaffarpur', 'Bhagalpur', 'Purnia', 'Darbhanga', 'Begusarai', 'Arrah', 'Katihar',
    'Munger', 'Chhapra', 'Saharsa', 'Sitamarhi', 'Hajipur', 'Siwan', 'Motihari', 'Nawada', 'Buxar',
    'Jehanabad', 'Aurangabad', 'Samastipur',
  ],
  CH: ['Chandigarh'],
  CG: [
    'Raipur', 'Bhilai', 'Bilaspur', 'Korba', 'Rajnandgaon', 'Raigarh', 'Jagdalpur', 'Ambikapur', 'Durg',
    'Bhatapara', 'Dhamtari', 'Chirmiri', 'Mahasamund', 'Janjgir', 'Kanker',
  ],
  DD: ['Daman', 'Diu', 'Silvassa', 'Dadra'],
  DL: [
    'New Delhi', 'Central Delhi', 'North Delhi', 'South Delhi', 'East Delhi', 'West Delhi', 'Dwarka',
    'Rohini', 'Pitampura', 'Karol Bagh', 'Lajpat Nagar', 'Vasant Kunj', 'Mayur Vihar',
  ],
  GA: ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda', 'Bicholim', 'Curchorem'],
  GJ: [
    'Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar', 'Jamnagar', 'Junagadh', 'Gandhinagar', 'Anand',
    'Bharuch', 'Mehsana', 'Morbi', 'Surendranagar', 'Godhra', 'Nadiad', 'Navsari', 'Vapi', 'Valsad',
    'Bhuj', 'Palanpur', 'Porbandar', 'Veraval', 'Botad', 'Patan',
  ],
  HR: [
    'Gurugram', 'Faridabad', 'Panipat', 'Ambala', 'Yamunanagar', 'Rohtak', 'Hisar', 'Karnal', 'Sonipat',
    'Panchkula', 'Bhiwani', 'Sirsa', 'Bahadurgarh', 'Rewari', 'Palwal', 'Jind', 'Kaithal', 'Thanesar',
    'Narnaul', 'Hansi',
  ],
  HP: [
    'Shimla', 'Manali', 'Dharamshala', 'Solan', 'Mandi', 'Bilaspur', 'Kullu', 'Chamba', 'Kangra', 'Una',
    'Hamirpur', 'Nahan', 'Palampur', 'Baddi', 'Parwanoo',
  ],
  JK: ['Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Udhampur', 'Kathua', 'Sopore', 'Rajouri', 'Pulwama', 'Kupwara'],
  JH: [
    'Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro Steel City', 'Deoghar', 'Hazaribagh', 'Giridih', 'Ramgarh',
    'Medininagar', 'Phusro', 'Adityapur', 'Chatra', 'Gumla', 'Lohardaga', 'Simdega', 'Khunti',
  ],
  KA: [
    'Bengaluru', 'Mysuru', 'Mangaluru', 'Hubballi', 'Belagavi', 'Kalaburagi', 'Davangere', 'Ballari', 'Vijayapura',
    'Tumakuru', 'Raichur', 'Udupi', 'Chitradurga', 'Kolar', 'Mandya', 'Hassan', 'Shivamogga', 'Bidar',
    'Bagalkot', 'Gadag', 'Haveri', 'Karwar', 'Ramanagara', 'Chikkamagaluru',
  ],
  KL: [
    'Kochi', 'Thiruvananthapuram', 'Kozhikode', 'Thrissur', 'Kollam', 'Kannur', 'Alappuzha', 'Palakkad',
    'Malappuram', 'Kottayam', 'Pathanamthitta', 'Idukki', 'Wayanad', 'Kasaragod', 'Vatakara',
  ],
  LA: ['Leh', 'Kargil', 'Diskit', 'Drass'],
  LD: ['Kavaratti', 'Agatti', 'Minicoy', 'Andrott'],
  MP: [
    'Indore', 'Bhopal', 'Jabalpur', 'Gwalior', 'Ujjain', 'Sagar', 'Dewas', 'Satna', 'Ratlam', 'Rewa',
    'Murwara', 'Singrauli', 'Burhanpur', 'Khandwa', 'Chhindwara', 'Shivpuri', 'Mandsaur', 'Neemuch',
    'Hoshangabad', 'Itarsi', 'Vidisha', 'Sehore', 'Morena', 'Bhind',
  ],
  MH: [
    'Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Aurangabad', 'Solapur', 'Thane', 'Navi Mumbai', 'Kalyan', 'Vasai-Virar',
    'Pimpri-Chinchwad', 'Amravati', 'Nanded', 'Kolhapur', 'Sangli', 'Malegaon', 'Jalgaon', 'Akola', 'Latur',
    'Ahmednagar', 'Dhule', 'Chandrapur', 'Parbhani', 'Ichalkaranji', 'Jalna', 'Bhusawal', 'Panvel', 'Satara',
    'Ratnagiri', 'Yavatmal', 'Wardha', 'Gondia',
  ],
  MN: ['Imphal', 'Thoubal', 'Bishnupur', 'Churachandpur', 'Ukhrul', 'Senapati'],
  ML: ['Shillong', 'Tura', 'Jowai', 'Nongstoin', 'Williamnagar'],
  MZ: ['Aizawl', 'Lunglei', 'Champhai', 'Saiha', 'Kolasib', 'Serchhip'],
  NL: ['Kohima', 'Dimapur', 'Mokokchung', 'Tuensang', 'Wokha', 'Mon', 'Phek'],
  OR: [
    'Bhubaneswar', 'Cuttack', 'Rourkela', 'Brahmapur', 'Sambalpur', 'Puri', 'Balasore', 'Bhadrak', 'Baripada',
    'Jharsuguda', 'Angul', 'Dhenkanal', 'Jeypore', 'Paradip', 'Kendujhar', 'Phulbani', 'Rayagada', 'Titlagarh',
  ],
  PY: ['Puducherry', 'Karaikal', 'Yanam', 'Mahe', 'Ozhukarai'],
  PB: [
    'Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda', 'Pathankot', 'Mohali', 'Hoshiarpur', 'Batala',
    'Moga', 'Abohar', 'Malerkotla', 'Khanna', 'Phagwara', 'Firozpur', 'Sangrur', 'Rupnagar', 'Kapurthala',
  ],
  RJ: [
    'Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Bikaner', 'Ajmer', 'Bhilwara', 'Alwar', 'Bharatpur', 'Sikar',
    'Pali', 'Sri Ganganagar', 'Tonk', 'Kishangarh', 'Beawar', 'Hanumangarh', 'Dhaulpur', 'Churu', 'Nagaur',
    'Barmer', 'Jaisalmer',
  ],
  SK: ['Gangtok', 'Namchi', 'Mangan', 'Gyalshing', 'Ravangla'],
  TN: [
    'Chennai', 'Coimbatore', 'Madurai', 'Salem', 'Tiruchirappalli', 'Tirunelveli', 'Thoothukudi', 'Nagercoil',
    'Thanjavur', 'Erode', 'Dindigul', 'Vellore', 'Tiruppur', 'Karaikudi', 'Cuddalore', 'Hosur', 'Kanchipuram',
    'Tiruvannamalai', 'Kumbakonam', 'Ooty', 'Pollachi', 'Rajapalayam', 'Sivakasi',
  ],
  TS: [
    'Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar', 'Ramagundam', 'Khammam', 'Mahbubnagar', 'Nalgonda',
    'Adilabad', 'Secunderabad', 'Mancherial', 'Jagtial', 'Siddipet', 'Kamareddy', 'Sangareddy', 'Medak',
  ],
  TR: ['Agartala', 'Udaipur', 'Dharmanagar', 'Kailashahar', 'Belonia', 'Ambassa'],
  UP: [
    'Lucknow', 'Kanpur', 'Noida', 'Varanasi', 'Agra', 'Meerut', 'Prayagraj', 'Bareilly', 'Ghaziabad', 'Gorakhpur',
    'Aligarh', 'Saharanpur', 'Jhansi', 'Moradabad', 'Faizabad', 'Firozabad', 'Mathura', 'Muzaffarnagar',
    'Shahjahanpur', 'Rampur', 'Mirzapur', 'Etawah', 'Budaun', 'Bahraich', 'Jaunpur', 'Lakhimpur', 'Sitapur',
    'Hardoi', 'Raebareli', 'Ayodhya', 'Bulandshahr', 'Amroha', 'Hapur', 'Sambhal',
  ],
  UK: [
    'Dehradun', 'Haridwar', 'Rishikesh', 'Nainital', 'Haldwani', 'Roorkee', 'Rudrapur', 'Kashipur', 'Pithoragarh',
    'Almora', 'Mussoorie', 'Kotdwar', 'Pauri', 'Tehri', 'Udham Singh Nagar',
  ],
  WB: [
    'Kolkata', 'Howrah', 'Siliguri', 'Durgapur', 'Asansol', 'Bardhaman', 'Malda', 'Kharagpur', 'Baharampur',
    'Haldia', 'Raiganj', 'Jalpaiguri', 'Krishnanagar', 'Bangaon', 'Cooch Behar', 'Alipurduar', 'Darjeeling',
    'Purulia', 'Bankura', 'Midnapore', 'Barasat',
  ],
};

export const CITY_COORDINATES: Record<string, { lat: number; lng: number }> = {
  // Tier 1 metros
  Mumbai: { lat: 19.0760, lng: 72.8777 },
  'New Delhi': { lat: 28.6139, lng: 77.2090 },
  Bengaluru: { lat: 12.9716, lng: 77.5946 },
  Hyderabad: { lat: 17.3850, lng: 78.4867 },
  Chennai: { lat: 13.0827, lng: 80.2707 },
  Pune: { lat: 18.5204, lng: 73.8567 },
  Ahmedabad: { lat: 23.0225, lng: 72.5714 },
  Kolkata: { lat: 22.5726, lng: 88.3639 },
  // Tier 2 major cities
  Jaipur: { lat: 26.9124, lng: 75.7873 },
  Surat: { lat: 21.1702, lng: 72.8311 },
  Lucknow: { lat: 26.8467, lng: 80.9462 },
  Chandigarh: { lat: 30.7333, lng: 76.7794 },
  Indore: { lat: 22.7196, lng: 75.8577 },
  Kochi: { lat: 9.9312, lng: 76.2673 },
  Guwahati: { lat: 26.1445, lng: 91.7362 },
  Bhopal: { lat: 23.2599, lng: 77.4126 },
  Bhubaneswar: { lat: 20.2961, lng: 85.8245 },
  Ranchi: { lat: 23.3441, lng: 85.3096 },
  Patna: { lat: 25.5941, lng: 85.1376 },
  Visakhapatnam: { lat: 17.6868, lng: 83.2185 },
  // State capitals & major tier-2/3 cities
  Nagpur: { lat: 21.1458, lng: 79.0882 },
  Nashik: { lat: 19.9975, lng: 73.7898 },
  Vadodara: { lat: 22.3072, lng: 73.1812 },
  Rajkot: { lat: 22.3039, lng: 70.8022 },
  Thiruvananthapuram: { lat: 8.5241, lng: 76.9366 },
  Kozhikode: { lat: 11.2588, lng: 75.7804 },
  Coimbatore: { lat: 11.0168, lng: 76.9558 },
  Madurai: { lat: 9.9252, lng: 78.1198 },
  Vijayawada: { lat: 16.5062, lng: 80.6480 },
  Warangal: { lat: 17.9784, lng: 79.5941 },
  Karimnagar: { lat: 18.4386, lng: 79.1288 },
  Guntur: { lat: 16.3067, lng: 80.4365 },
  Tirupati: { lat: 13.6288, lng: 79.4192 },
  Mysuru: { lat: 12.2958, lng: 76.6394 },
  Mangaluru: { lat: 12.9141, lng: 74.8560 },
  Hubli: { lat: 15.3647, lng: 75.1240 },
  Jodhpur: { lat: 26.2389, lng: 73.0243 },
  Udaipur: { lat: 24.5854, lng: 73.7125 },
  Kota: { lat: 25.2138, lng: 75.8648 },
  Agra: { lat: 27.1767, lng: 78.0081 },
  Varanasi: { lat: 25.3176, lng: 82.9739 },
  Kanpur: { lat: 26.4499, lng: 80.3319 },
  Noida: { lat: 28.5355, lng: 77.3910 },
  Ghaziabad: { lat: 28.6692, lng: 77.4538 },
  Meerut: { lat: 28.9845, lng: 77.7064 },
  Prayagraj: { lat: 25.4358, lng: 81.8463 },
  Gorakhpur: { lat: 26.7606, lng: 83.3732 },
  Dehradun: { lat: 30.3165, lng: 78.0322 },
  Haridwar: { lat: 29.9457, lng: 78.1642 },
  Gurugram: { lat: 28.4595, lng: 77.0266 },
  Faridabad: { lat: 28.4089, lng: 77.3178 },
  Ludhiana: { lat: 30.9010, lng: 75.8573 },
  Amritsar: { lat: 31.6340, lng: 74.8723 },
  Jalandhar: { lat: 31.3260, lng: 75.5762 },
  Jammu: { lat: 32.7266, lng: 74.8570 },
  Srinagar: { lat: 34.0837, lng: 74.7973 },
  Shimla: { lat: 31.1048, lng: 77.1734 },
  Panaji: { lat: 15.4909, lng: 73.8278 },
  'Port Blair': { lat: 11.6234, lng: 92.7265 },
  Imphal: { lat: 24.8170, lng: 93.9368 },
  Shillong: { lat: 25.5788, lng: 91.8933 },
  Aizawl: { lat: 23.7271, lng: 92.7176 },
  Kohima: { lat: 25.6751, lng: 94.1086 },
  Agartala: { lat: 23.8315, lng: 91.2868 },
  Itanagar: { lat: 27.0844, lng: 93.6053 },
  Gangtok: { lat: 27.3389, lng: 88.6065 },
  Leh: { lat: 34.1526, lng: 77.5771 },
  Raipur: { lat: 21.2514, lng: 81.6296 },
  Jabalpur: { lat: 23.1815, lng: 79.9864 },
  Gwalior: { lat: 26.2183, lng: 78.1828 },
  Jamshedpur: { lat: 22.8046, lng: 86.2029 },
  Dhanbad: { lat: 23.7957, lng: 86.4304 },
  Siliguri: { lat: 26.7271, lng: 88.6393 },
  Durgapur: { lat: 23.5204, lng: 87.3119 },
  Salem: { lat: 11.6643, lng: 78.1460 },
  Tiruchirappalli: { lat: 10.7905, lng: 78.7047 },
  Solapur: { lat: 17.6599, lng: 75.9064 },
  Thane: { lat: 19.2183, lng: 72.9781 },
  'Navi Mumbai': { lat: 19.0330, lng: 73.0297 },
  Aurangabad: { lat: 19.8762, lng: 75.3433 },
  Kolhapur: { lat: 16.7050, lng: 74.2433 },
  Bikaner: { lat: 28.0229, lng: 73.3119 },
  Ajmer: { lat: 26.4499, lng: 74.6399 },
  Bhavnagar: { lat: 21.7645, lng: 72.1519 },
  Jamnagar: { lat: 22.4707, lng: 70.0577 },
  Rohtak: { lat: 28.8955, lng: 76.5796 },
  Panipat: { lat: 29.3909, lng: 76.9635 },
  Bathinda: { lat: 30.2110, lng: 74.9455 },
  Cuttack: { lat: 20.4625, lng: 85.8830 },
  Rourkela: { lat: 22.2604, lng: 84.8536 },
  Puducherry: { lat: 11.9416, lng: 79.8083 },
  Thrissur: { lat: 10.5276, lng: 76.2144 },
  Nizamabad: { lat: 18.6725, lng: 78.0941 },
  Secunderabad: { lat: 17.4399, lng: 78.4983 },
  Nellore: { lat: 14.4426, lng: 79.9865 },
  Rajahmundry: { lat: 17.0005, lng: 81.8040 },
  Bilaspur: { lat: 22.0797, lng: 82.1409 },
  Muzaffarpur: { lat: 26.1209, lng: 85.3647 },
};
