/** English i18n keys for static marketing / support pages (spread into lib/i18n.ts `en`). */
export const staticPageEn = {
  // About Us
  'about.badge': 'About ReRide',
  'about.hero.title': 'Used cars & car care, made simple',
  'about.hero.subtitle':
    'A simple, India-first platform that connects buyers, sellers, and verified workshops — all in one place.',
  'about.stat1.label': 'India-first',
  'about.stat2.label': 'Buy • Sell • Service',
  'about.stat3.label': 'Verified workshops',
  'about.whatWeDo.title': 'What we do',
  'about.whatWeDo.body':
    'ReRide helps buyers discover quality used vehicles and connects them with sellers and dealers. We also offer car services as a marketplace: you book with confidence, and verified workshops fulfil the work. We are the platform between customers and providers—not the workshop ourselves.',
  'about.why.title': 'Why ReRide',
  'about.feature1.title': 'Focused experience',
  'about.feature1.desc': 'Browse, compare, chat, and book service without the clutter.',
  'about.feature2.title': 'Built for India',
  'about.feature2.desc': 'Local cities, ₹ pricing, and support channels people actually use.',
  'about.feature3.title': 'Trust-first',
  'about.feature3.desc': 'We invest in verification, safety tips, and clear policies.',
  'about.contact.title': 'Contact',
  'about.contact.body': 'Questions or partnership enquiries? Reach us through Support or call {{phone}}.',
  'about.contact.bodyNoPhone': 'Questions or partnership enquiries? Reach us through Support.',
  'about.contact.cta': 'Go to Support',

  // Safety Center
  'safety.badge': 'Trust & safety',
  'safety.hero.title': 'Stay in control, reduce risk',
  'safety.hero.subtitle':
    'Practical tips for buying, selling, and meeting on ReRide — so every deal stays safe and stress-free.',
  'safety.buying.title': 'Buying a used car',
  'safety.buying.tip1':
    'Inspect the vehicle in daylight; check service history, VIN, and RC where possible.',
  'safety.buying.tip2':
    'Prefer verified listings and clear photos; ask for an independent inspection if unsure.',
  'safety.buying.tip3':
    'Never pay full amounts upfront to strangers; use agreed milestones and documented transfers.',
  'safety.selling.title': 'Selling',
  'safety.selling.tip1': 'Meet buyers in safe, public places; consider bringing someone with you.',
  'safety.selling.tip2':
    'Share accurate condition and paperwork; misrepresentation hurts trust and can cause disputes.',
  'safety.selling.tip3': 'Confirm payment before handing over keys and documents.',
  'safety.scams.title': 'Scams & red flags',
  'safety.scams.tip1': 'Pressure to move off-platform, unusual payment apps, or “shipping only” deals.',
  'safety.scams.tip2': 'Prices far below market with excuses for no inspection or test drive.',
  'safety.scams.tip3': 'Requests for OTPs, passwords, or full card details over chat.',
  'safety.help.title': 'Need help?',
  'safety.help.body':
    'Report suspicious behaviour from the listing or inbox, or contact Support. For emergencies, contact local authorities.',
  'safety.help.cta': 'Contact support',

  // Support
  'support.badge': 'Priority support that actually answers',
  'support.hero.title': 'Contact Support',
  'support.hero.subtitle':
    "Tell us what you need. We'll route your request to the right specialist and keep you posted every step of the way.",
  'support.stat.response': 'Avg. response under 30 mins',
  'support.stat.satisfaction': '4.8/5 satisfaction',
  'support.urgent.title': 'Need urgent help?',
  'support.urgent.body': 'We monitor tickets around the clock.',
  'support.card.badge': 'Fastest Resolution',
  'support.card.title': 'We pair every ticket with a specialist',
  'support.card.body':
    "Share a few details and we'll triage, prioritize, and keep you updated. 90% of tickets are resolved without a follow-up.",
  'support.category.service': 'Car service & detailing',
  'support.category.buySell': 'Buying & selling help',
  'support.category.payments': 'Payments & RC',
  'support.category.app': 'App issues',
  'support.quickReach.eyebrow': 'Quick reach',
  'support.quickReach.title': 'Prefer a faster lane?',
  'support.quickReach.call.title': 'Call us',
  'support.quickReach.call.desc': 'Mon-Sat, 9am-8pm',
  'support.quickReach.whatsapp.title': 'WhatsApp',
  'support.quickReach.whatsapp.desc': 'Quick status updates',
  'support.quickReach.email.title': 'Email',
  'support.quickReach.email.desc': 'support@reride.com',
  'support.quickReach.openMail': 'Open mail',
  'support.form.name': 'Your Name',
  'support.form.email': 'Your Email',
  'support.form.subject': 'Subject',
  'support.form.message': 'Message',
  'support.form.namePlaceholder': 'Enter your full name',
  'support.form.emailPlaceholder': 'your.email@example.com',
  'support.form.subjectPlaceholder': 'Brief description of your issue',
  'support.form.messagePlaceholder': 'Share more context to help us resolve this quickly...',
  'support.form.submit': 'Submit Ticket',
  'support.form.submitting': 'Submitting…',
  'support.success.title': 'Ticket submitted!',
  'support.success.body': "We've received your request and will reach out shortly.",

  // Sell Car (landing / step 0)
  'sellCar.hero.title': 'Sell Car Online',
  'sellCar.hero.subtitle': 'at the Best Price',
  'sellCar.step0.badge': 'Faster handoffs, happier sellers',
  'sellCar.step0.title': 'Sell with confidence, in under 2 minutes',
  'sellCar.step0.subtitle':
    'Step-by-step guidance, auto-fetched details, verified buyers, and instant payouts.',
  'sellCar.trust.free.value': 'Free',
  'sellCar.trust.free.label': 'To list your vehicle',
  'sellCar.trust.direct.value': 'Direct',
  'sellCar.trust.direct.label': 'Buyer contact',
  'sellCar.trust.panIndia.value': 'Pan-India',
  'sellCar.trust.panIndia.label': 'City coverage',
  'sellCar.highlight1.title': 'Instant valuation',
  'sellCar.highlight1.desc': '90% cars get a price in under 2 minutes.',
  'sellCar.highlight2.title': 'Doorstep inspection',
  'sellCar.highlight2.desc': 'Free pickup & RC transfer included.',
  'sellCar.highlight3.title': 'Transparent listings',
  'sellCar.highlight3.desc': 'Add RC, photos, and details buyers can verify.',
  'sellCar.step0.pickOne': 'Pick one to begin',
  'sellCar.step0.whoSelling': "Who's selling?",
  'sellCar.individual.title': 'Sell as Individual',
  'sellCar.individual.recommended': 'Recommended',
  'sellCar.individual.desc': 'One-to-one guidance, instant valuation, free RC transfer.',
  'sellCar.individual.tag1': '2-min flow',
  'sellCar.individual.tag2': 'Instant price',
  'sellCar.individual.tag3': 'Doorstep pickup',
  'sellCar.dealer.title': 'Sell as Dealer',
  'sellCar.dealer.desc': 'Log in to your dealer account and manage inventory.',
  'sellCar.dealer.tag1': 'Bulk listing',
  'sellCar.dealer.tag2': 'Lead inbox',
  'sellCar.dealer.tag3': 'Priority support',
  'sellCar.step0.help':
    'Need help? Call 727-727-7275 or chat with us — we answer in under 60 seconds.',
  'sellCar.back': 'Back',

  // Mobile Sell Car
  'sellCar.mobile.title': 'Sell Your Car',
  'sellCar.mobile.step0.title': 'I am a',
  'sellCar.mobile.individual.title': 'Individual',
  'sellCar.mobile.individual.desc': 'Selling my personal vehicle',
  'sellCar.mobile.dealer.title': 'Dealer',
  'sellCar.mobile.dealer.desc': 'I have a dealership',

  // Mobile Support
  'support.mobile.badge': 'Support',
  'support.mobile.hero.title': 'How can we help?',
  'support.mobile.hero.subtitle': 'Send us a ticket — we typically reply within a day.',
  'support.mobile.email.label': 'Email us',
  'support.mobile.form.eyebrow': 'New ticket',
  'support.mobile.form.title': "Tell us what's happening",
  'support.mobile.form.name': 'Name',
  'support.mobile.form.namePlaceholder': 'Your name',
  'support.mobile.form.messagePlaceholder': 'Describe your issue in detail...',
  'support.mobile.form.submit': 'Submit ticket',
  'support.mobile.success.title': 'Ticket submitted',
  'support.mobile.success.body': "We'll get back to you shortly.",
  'support.mobile.error.submit': 'Failed to submit support ticket. Please try again.',
  'support.mobile.validation.name': 'Name is required',
  'support.mobile.validation.email': 'Email is required',
  'support.mobile.validation.emailInvalid': 'Please enter a valid email address',
  'support.mobile.validation.subject': 'Subject is required',
  'support.mobile.validation.message': 'Message is required',

  // Service detail (UI chrome)
  'serviceDetail.back': 'Back to Services',
  'serviceDetail.included.title': 'Services Included',
  'serviceDetail.included.atCheckout': 'At checkout',
  'serviceDetail.why.title': 'Why Choose This Service?',
  'serviceDetail.quality.title': 'Service Quality Assured',
  'serviceDetail.quality.oem.title': 'OEM Parts Only',
  'serviceDetail.quality.oem.desc': 'Only OEM or brand-authorised parts used',
  'serviceDetail.quality.warranty.title': '3-Month Warranty',
  'serviceDetail.quality.warranty.desc': 'Service warranty on parts & workmanship',
  'serviceDetail.quality.updates.title': 'Real-Time Updates',
  'serviceDetail.quality.updates.desc': 'Track your service progress live',
  'serviceDetail.quality.photos.title': 'Pre & Post Photos',
  'serviceDetail.quality.photos.desc': 'Complete documentation of service',
  'serviceDetail.pricing.title': 'Pricing & Booking',
  'serviceDetail.pricing.finalLabel': 'Final price',
  'serviceDetail.pricing.confirmed': 'Price confirmed at checkout',
  'serviceDetail.pricing.body':
    "We'll match you with a nearby verified service provider based on your location. Final pricing may vary by provider, vehicle model, and pickup/drop preference.",
  'serviceDetail.pricing.typicalRange': 'Typical range',
  'serviceDetail.pricing.rangeHint': 'Estimated range only. Final price is shown before payment.',
  'serviceDetail.pricing.feature1': 'Final breakup before payment',
  'serviceDetail.pricing.feature2': '3-month warranty',
  'serviceDetail.pricing.feature3': 'Verified workshops',
  'serviceDetail.pricing.feature4': 'Doorstep pickup available',
  'serviceDetail.pricing.featureProvider': 'Provider selected based on location',
  'serviceDetail.pricing.featurePickup': 'Pickup & drop available',
  'serviceDetail.pricing.featureUpdates': 'Real-time updates',
  'serviceDetail.loading': 'Loading service details...',
  'serviceDetail.bookNow': 'Book Now',
  'serviceDetail.addToCart': 'Add to Cart',
  'serviceDetail.callForQuote': 'Call for Quote',
  'serviceDetail.contactSupport': 'Contact support',
  'serviceDetail.secure': 'Secure',
  'serviceDetail.verified': 'Verified',
} as const;
