/** Toast and inline error strings for AppProvider (synced across en, hi, te, ta). */
export const toastEn: Record<string, string> = {
  'errors.network': 'Unable to connect to the server. Please check your internet connection.',
  'errors.timeout': 'Request timed out. Please try again.',
  'errors.permission': 'You do not have permission to perform this action.',
  'toast.loadingVehicles': 'Loading vehicles...',
  'toast.loggedOut': 'You have been logged out.',
  'toast.loginInvalidUser': 'Login failed: Invalid user data. Please try again.',
  'toast.loginInvalidRole': 'Login failed: Invalid user role. Please try again.',
  'toast.welcomeBack': 'Welcome back, {{name}}!',
  'toast.googleSignInFailed': 'Could not finish Google sign-in',
  'toast.registerInvalidUser': 'Registration failed: Invalid user data. Please try again.',
  'toast.registerInvalidRole': 'Registration failed: Invalid user role. Please try again.',
  'toast.welcomeNewUser': 'Welcome to ReRide, {{name}}!',
  'toast.loadedVehiclesCount': 'Loaded {{count}} vehicles',
  'toast.serviceUnavailableAdmin':
    'Service unavailable. If you manage this site, set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in Vercel → Environment Variables (Production), then redeploy.',
  'toast.vehiclesLoadFailedShort': 'Could not load vehicles. Check your connection and try again.',
  'toast.someDataFailedLoad': 'Some data failed to load. The app will continue with available data.',
  'toast.listingsEmptyDbUnavailable':
    'Listings are empty because the server database is not available (Supabase config missing). If you manage this site, set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY, then redeploy.',
  'toast.vehiclesLoadFailed': 'Could not load vehicles. Please check your connection and try again.',
  'toast.dealersEmptyDbUnavailable':
    'Dealer details are empty because the server database is not available (Supabase config missing). If you manage this site, set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY, then redeploy.',
  'toast.usersLoadFailed': 'Could not load users. Please try again.',
  'toast.syncedItemsCount': 'Synced {{count}} items to server',
  'toast.dataSyncSuccess': 'Data synchronized successfully',
  'toast.dataSyncPartial': 'Data sync failed, but app is still functional',
  'toast.nowOffline': 'You are now offline. Changes will sync when connection is restored.',
  'toast.vehicleNotFound': 'Vehicle not found',
  'toast.vehicleUpdatedSuccess': 'Vehicle updated successfully',
  'toast.vehicleStatusUpdated': 'Vehicle status updated to {{status}}',
  'toast.vehicleFeaturedSuccess': 'Vehicle featured successfully',
  'toast.vehicleUnfeaturedSuccess': 'Vehicle unfeatured successfully',
  'toast.vehicleUpdateFailed': 'Failed to update vehicle. Please try again.',
  'toast.vehicleSyncFailedDetail': 'Failed to sync update to server: {{detail}}',
  'toast.userUpdated': 'User {{email}} updated successfully',
  'toast.userCreateFailedDetail': 'User creation failed: {{reason}}',
  'toast.userCreated': 'User {{name}} created successfully',
  'toast.planUpdateFailed': 'Failed to update user plan. Please try again.',
  'toast.planUpdated': 'Plan updated for {{email}}',
  'toast.userStatusToggled': 'User status toggled for {{email}}',
  'toast.userStatusToggleFailed': 'Failed to toggle user status',
  'toast.vehicleStatusUpdateFailed': 'Failed to update vehicle status',
  'toast.vehicleAlreadyFeatured': 'Vehicle is already featured.',
  'toast.vehicleFeaturedWithCredits': 'Vehicle featured successfully. Credits remaining: {{credits}}',
  'toast.featureVehicleFailed': 'Failed to feature vehicle. Please try again.',
  'toast.featureStatusFailed': 'Failed to update vehicle feature status',
  'toast.conversationNotFound': 'Conversation not found',
  'toast.flagResolvedVehicle': 'Flag resolved for vehicle',
  'toast.flagResolvedConversation': 'Flag resolved for conversation',
  'toast.flagResolveFailedVehicle': 'Failed to resolve vehicle flag',
  'toast.flagResolveFailedConversation': 'Failed to resolve conversation flag',
  'toast.settingsUpdated': 'Platform settings updated',
  'toast.broadcastSent': 'Broadcast sent to all users',
  'toast.exportUsersSuccess': 'Exported {{count}} users successfully',
  'toast.exportFailed': 'Export failed. Please try again.',
  'toast.importUsersSuccess': 'Successfully imported {{count}} user(s)',
  'toast.importUsersPartialWarning': '{{count}} user(s) failed to import',
  'toast.exportVehiclesSuccess': 'Exported {{count}} vehicles successfully',
  'toast.importVehiclesSuccess': 'Successfully imported {{count}} vehicle(s)',
  'toast.importVehiclesPartialWarning': '{{count}} vehicle(s) failed to import',
  'toast.exportSalesSuccess': 'Exported {{count}} sales records successfully',
  'toast.vehicleDataUpdateFailed': 'Vehicle data update failed. Please try again.',
  'toast.vehicleDataUpdated': 'Vehicle data updated successfully',
  'toast.verificationToggled': 'Verification status toggled for {{email}}',
  'toast.supportTicketUpdated': 'Support ticket updated',
  'toast.supportTicketUpdateFailed': 'Failed to update support ticket',
  'toast.faqAdded': 'FAQ added successfully',
  'toast.faqAddFailed': 'FAQ creation failed. Please try again.',
  'toast.faqUpdated': 'FAQ updated successfully',
  'toast.faqUpdateFailed': 'FAQ update failed. Please try again.',
  'toast.faqDeleted': 'FAQ deleted successfully',
  'toast.faqDeleteFailed': 'FAQ deletion failed. Please try again.',
  'toast.certificationApproved': 'Certification approved for vehicle',
  'toast.certificationRejected': 'Certification rejected for vehicle',
  'toast.certificationUpdateFailed': 'Certification update failed',
  'toast.ratingAdded': 'Rating added successfully',
  'toast.sellerRatingAdded': 'Seller rating added successfully',
  'toast.loginRequiredMessages': 'You must be logged in to send messages.',
  'toast.conversationNotFoundRefresh': 'Conversation not found. Please refresh and try again.',
  'toast.failedSendMessageConnection': 'Failed to send message. Please check your connection.',
  'toast.failedSendMessageGeneric': 'Failed to send message. Please try again.',
  'toast.contentFlagged': 'Content flagged for review{{reasonSuffix}}',
  'toast.passwordUpdatedSuccess': 'Password updated successfully!',
  'toast.profileUpdatedSuccess': 'Profile updated successfully!',
  'toast.passwordUpdateFailedReason': 'Password update failed: {{reason}}',
  'toast.profileUpdateFailedReason': 'Profile update failed: {{reason}}',
  'toast.passwordUpdateFailedServer': 'Password update failed: Server error. Please try again.',
  'toast.profileUpdateFailedServer': 'Profile update failed: Server error. Please try again.',
  'toast.passwordUpdateFailedSupabase': 'Password update failed: Supabase connection error. Please try again.',
  'toast.profileUpdateFailedSupabase': 'Profile update failed: Supabase connection error. Please try again.',
  'toast.passwordUpdateFailedNetwork':
    'Password update failed: Network error. Please check your connection and try again.',
  'toast.profileUpdateFailedNetwork':
    'Profile update failed: Network error. Please check your connection and try again.',
  'toast.passwordUpdateFailedNotFound': 'Password update failed: API endpoint not found. Please check deployment.',
  'toast.profileUpdateFailedNotFound': 'Profile update failed: API endpoint not found. Please check deployment.',
  'toast.updateInvalidData': 'Update failed: Invalid data - {{detail}}',
  'toast.passwordUpdateFailedServerRetry': 'Password update failed: Server error. Please try again.',
  'toast.profileUpdateFailedServerRetry': 'Profile update failed: Server error. Please try again.',
  'toast.passwordUpdateFailedDisplay': 'Password update failed: {{error}}',
  'toast.profileUpdateFailedDisplay': 'Profile update failed: {{error}}',
  'toast.passwordUpdateFailedCheckLogs': 'Password update failed. Please try again or check server logs.',
  'toast.profileUpdateFailedTryAgain': 'Profile update failed. Please try again.',
  'toast.userDeletedSuccess': 'User deleted successfully',
  'toast.vehicleDeletedSuccess': 'Vehicle deleted successfully',
  'toast.deleteVehicleFailed': 'Failed to delete vehicle',
  'toast.deleteVehicleFailedRetry': 'Failed to delete vehicle. Please try again.',
  'toast.offerAccepted': 'Offer accepted successfully',
  'toast.offerRejected': 'Offer rejected successfully',
  'toast.offerCountered': 'Offer countered successfully',
  'toast.unknownError': 'Unknown error',
  'vehicle.share.copyLink': 'Copy Link',
  'vehicle.share.copied': 'Copied!',
  'vehicle.share.failed': 'Failed!',
  'vehicle.detail.photosTap': '{{count}} photos • Tap to view',
};

export const toastHi: Record<string, string> = {
  'errors.network': 'सर्वर से कनेक्ट नहीं हो सका। अपना इंटरनेट जांचें।',
  'errors.timeout': 'अनुरोध समय समाप्त। पुनः प्रयास करें।',
  'errors.permission': 'इस क्रिया की अनुमति नहीं है।',
  'toast.loadingVehicles': 'वाहन लोड हो रहे हैं...',
  'toast.loggedOut': 'आप लॉग आउट हो गए।',
  'toast.loginInvalidUser': 'लॉगिन विफल: उपयोगकर्ता डेटा अमान्य। पुनः प्रयास करें।',
  'toast.loginInvalidRole': 'लॉगिन विफल: भूमिका अमान्य। पुनः प्रयास करें।',
  'toast.welcomeBack': 'वापसी पर स्वागत है, {{name}}!',
  'toast.googleSignInFailed': 'Google साइन-इन पूरा नहीं हो सका',
  'toast.registerInvalidUser': 'पंजीकरण विफल: उपयोगकर्ता डेटा अमान्य।',
  'toast.registerInvalidRole': 'पंजीकरण विफल: भूमिका अमान्य।',
  'toast.welcomeNewUser': 'ReRide में स्वागत है, {{name}}!',
  'toast.loadedVehiclesCount': '{{count}} वाहन लोड किए गए',
  'toast.serviceUnavailableAdmin':
    'सेवा अनुपलब्ध। यदि आप साइट प्रबंधित करते हैं, तो Vercel में SUPABASE_URL और SUPABASE_SERVICE_ROLE_KEY सेट करके पुनः डिप्लॉय करें।',
  'toast.vehiclesLoadFailedShort': 'वाहन लोड नहीं हो सके। कनेक्शन जांचें।',
  'toast.someDataFailedLoad': 'कुछ डेटा लोड नहीं हुआ। ऐप उपलब्ध डेटा के साथ चलेगा।',
  'toast.listingsEmptyDbUnavailable':
    'लिस्टिंग खाली है क्योंकि डेटाबेस उपलब्ध नहीं (Supabase कॉन्फ़िग)। प्रबंधकों: SUPABASE_URL और SUPABASE_SERVICE_ROLE_KEY सेट करें।',
  'toast.vehiclesLoadFailed': 'वाहन लोड नहीं हो सके। कनेक्शन जांचकर पुनः प्रयास करें।',
  'toast.dealersEmptyDbUnavailable':
    'डीलर विवरण खाली: सर्वर डेटाबेस उपलब्ध नहीं। प्रबंधकों: Supabase कुंजियाँ सेट करें और पुनः डिप्लॉय करें।',
  'toast.usersLoadFailed': 'उपयोगकर्ता लोड नहीं हो सके। पुनः प्रयास करें।',
  'toast.syncedItemsCount': 'सर्वर पर {{count}} आइटम सिंक किए गए',
  'toast.dataSyncSuccess': 'डेटा सफलतापूर्वक सिंक हुआ',
  'toast.dataSyncPartial': 'डेटा सिंक विफल, ऐप फिर भी चलेगा',
  'toast.nowOffline': 'आप ऑफ़लाइन हैं। कनेक्शन बहाल होने पर सिंक होगा।',
  'toast.vehicleNotFound': 'वाहन नहीं मिला',
  'toast.vehicleUpdatedSuccess': 'वाहन सफलतापूर्वक अपडेट हुआ',
  'toast.vehicleStatusUpdated': 'वाहन स्थिति अपडेट: {{status}}',
  'toast.vehicleFeaturedSuccess': 'वाहन फीचर्ड किया गया',
  'toast.vehicleUnfeaturedSuccess': 'वाहन अनफीचर्ड किया गया',
  'toast.vehicleUpdateFailed': 'वाहन अपडेट विफल। पुनः प्रयास करें।',
  'toast.vehicleSyncFailedDetail': 'सर्वर सिंक विफल: {{detail}}',
  'toast.userUpdated': 'उपयोगकर्ता {{email}} अपडेट हुआ',
  'toast.userCreateFailedDetail': 'उपयोगकर्ता बनाना विफल: {{reason}}',
  'toast.userCreated': 'उपयोगकर्ता {{name}} बनाया गया',
  'toast.planUpdateFailed': 'प्लान अपडेट विफल। पुनः प्रयास करें।',
  'toast.planUpdated': '{{email}} का प्लान अपडेट हुआ',
  'toast.userStatusToggled': '{{email}} की स्थिति बदली गई',
  'toast.userStatusToggleFailed': 'उपयोगकर्ता स्थिति बदलने में विफल',
  'toast.vehicleStatusUpdateFailed': 'वाहन स्थिति अपडेट विफल',
  'toast.vehicleAlreadyFeatured': 'वाहन पहले से फीचर्ड है।',
  'toast.vehicleFeaturedWithCredits': 'वाहन फीचर्ड। शेष क्रेडिट: {{credits}}',
  'toast.featureVehicleFailed': 'वाहन फीचर करने में विफल।',
  'toast.featureStatusFailed': 'फीचर स्थिति अपडेट विफल',
  'toast.conversationNotFound': 'बातचीत नहीं मिली',
  'toast.flagResolvedVehicle': 'वाहन फ्लैग हल किया गया',
  'toast.flagResolvedConversation': 'बातचीत फ्लैग हल किया गया',
  'toast.flagResolveFailedVehicle': 'वाहन फ्लैग हल करने में विफल',
  'toast.flagResolveFailedConversation': 'बातचीत फ्लैग हल करने में विफल',
  'toast.settingsUpdated': 'प्लेटफ़ॉर्म सेटिंग अपडेट',
  'toast.broadcastSent': 'सभी उपयोगकर्ताओं को संदेश भेजा गया',
  'toast.exportUsersSuccess': '{{count}} उपयोगकर्ता निर्यात सफल',
  'toast.exportFailed': 'निर्यात विफल। पुनः प्रयास करें।',
  'toast.importUsersSuccess': '{{count}} उपयोगकर्ता आयात सफल',
  'toast.importUsersPartialWarning': '{{count}} उपयोगकर्ता आयात विफल',
  'toast.exportVehiclesSuccess': '{{count}} वाहन निर्यात सफल',
  'toast.importVehiclesSuccess': '{{count}} वाहन आयात सफल',
  'toast.importVehiclesPartialWarning': '{{count}} वाहन आयात विफल',
  'toast.exportSalesSuccess': '{{count}} बिक्री रिकॉर्ड निर्यात सफल',
  'toast.vehicleDataUpdateFailed': 'वाहन डेटा अपडेट विफल।',
  'toast.vehicleDataUpdated': 'वाहन डेटा अपडेट सफल',
  'toast.verificationToggled': '{{email}} का सत्यापन स्थिति बदली',
  'toast.supportTicketUpdated': 'सपोर्ट टिकट अपडेट',
  'toast.supportTicketUpdateFailed': 'टिकट अपडेट विफल',
  'toast.faqAdded': 'FAQ जोड़ा गया',
  'toast.faqAddFailed': 'FAQ जोड़ना विफल।',
  'toast.faqUpdated': 'FAQ अपडेट',
  'toast.faqUpdateFailed': 'FAQ अपडेट विफल',
  'toast.faqDeleted': 'FAQ हटाया गया',
  'toast.faqDeleteFailed': 'FAQ हटाना विफल',
  'toast.certificationApproved': 'प्रमाणन स्वीकृत',
  'toast.certificationRejected': 'प्रमाणन अस्वीकृत',
  'toast.certificationUpdateFailed': 'प्रमाणन अपडेट विफल',
  'toast.ratingAdded': 'रेटिंग जोड़ी गई',
  'toast.sellerRatingAdded': 'विक्रेता रेटिंग जोड़ी गई',
  'toast.loginRequiredMessages': 'संदेश भेजने के लिए लॉग इन करें।',
  'toast.conversationNotFoundRefresh': 'बातचीत नहीं मिली। रिफ्रेश करें।',
  'toast.failedSendMessageConnection': 'संदेश भेजने में विफल। कनेक्शन जांचें।',
  'toast.failedSendMessageGeneric': 'संदेश भेजने में विफल।',
  'toast.contentFlagged': 'समीक्षा के लिए फ्लैग किया गया{{reasonSuffix}}',
  'toast.passwordUpdatedSuccess': 'पासवर्ड अपडेट सफल!',
  'toast.profileUpdatedSuccess': 'प्रोफ़ाइल अपडेट सफल!',
  'toast.passwordUpdateFailedReason': 'पासवर्ड अपडेट विफल: {{reason}}',
  'toast.profileUpdateFailedReason': 'प्रोफ़ाइल अपडेट विफल: {{reason}}',
  'toast.passwordUpdateFailedServer': 'पासवर्ड: सर्वर त्रुटि। पुनः प्रयास करें।',
  'toast.profileUpdateFailedServer': 'प्रोफ़ाइल: सर्वर त्रुटि। पुनः प्रयास करें।',
  'toast.passwordUpdateFailedSupabase': 'पासवर्ड: Supabase कनेक्शन त्रुटि।',
  'toast.profileUpdateFailedSupabase': 'प्रोफ़ाइल: Supabase कनेक्शन त्रुटि।',
  'toast.passwordUpdateFailedNetwork': 'पासवर्ड: नेटवर्क त्रुटि। कनेक्शन जांचें।',
  'toast.profileUpdateFailedNetwork': 'प्रोफ़ाइल: नेटवर्क त्रुटि। कनेक्शन जांचें।',
  'toast.passwordUpdateFailedNotFound': 'पासवर्ड: API नहीं मिला। डिप्लॉयमेंट जांचें।',
  'toast.profileUpdateFailedNotFound': 'प्रोफ़ाइल: API नहीं मिला। डिप्लॉयमेंट जांचें।',
  'toast.updateInvalidData': 'अपडेट विफल: अमान्य डेटा - {{detail}}',
  'toast.passwordUpdateFailedServerRetry': 'पासवर्ड: सर्वर त्रुटि। पुनः प्रयास करें।',
  'toast.profileUpdateFailedServerRetry': 'प्रोफ़ाइल: सर्वर त्रुटि। पुनः प्रयास करें।',
  'toast.passwordUpdateFailedDisplay': 'पासवर्ड अपडेट विफल: {{error}}',
  'toast.profileUpdateFailedDisplay': 'प्रोफ़ाइल अपडेट विफल: {{error}}',
  'toast.passwordUpdateFailedCheckLogs': 'पासवर्ड अपडेट विफल। लॉग देखें।',
  'toast.profileUpdateFailedTryAgain': 'प्रोफ़ाइल अपडेट विफल। पुनः प्रयास करें।',
  'toast.userDeletedSuccess': 'उपयोगकर्ता हटाया गया',
  'toast.vehicleDeletedSuccess': 'वाहन हटाया गया',
  'toast.deleteVehicleFailed': 'वाहन हटाना विफल',
  'toast.deleteVehicleFailedRetry': 'वाहन हटाना विफल। पुनः प्रयास करें।',
  'toast.offerAccepted': 'ऑफ़र स्वीकार हुआ',
  'toast.offerRejected': 'ऑफ़र अस्वीकृत हुआ',
  'toast.offerCountered': 'काउंटर ऑफ़र भेजा गया',
  'toast.unknownError': 'अज्ञात त्रुटि',
  'vehicle.share.copyLink': 'लिंक कॉपी करें',
  'vehicle.share.copied': 'कॉपी हो गया!',
  'vehicle.share.failed': 'विफल!',
  'vehicle.detail.photosTap': '{{count}} फोटो • देखने के लिए टैप करें',
};

export const toastTe: Record<string, string> = {
  'errors.network': 'సర్వర్‌కు కనెక్ట్ కాలేకపోయాం. ఇంటర్నెట్ చూడండి.',
  'errors.timeout': 'అభ్యర్థన సమయం ముగిసింది. మళ్లీ ప్రయత్నించండి.',
  'errors.permission': 'ఈ చర్యకు అనుమతి లేదు.',
  'toast.loadingVehicles': 'వాహనాలు లోడ్ అవుతున్నాయి...',
  'toast.loggedOut': 'మీరు లాగ్ అవుట్ అయ్యారు.',
  'toast.loginInvalidUser': 'లాగిన్ విఫలం: చెల్లని వినియోగదారు డేటా.',
  'toast.loginInvalidRole': 'లాగిన్ విఫలం: చెల్లని పాత్ర.',
  'toast.welcomeBack': 'తిరిగి స్వాగతం, {{name}}!',
  'toast.googleSignInFailed': 'Google సైన్-ఇన్ పూర్తి కాలేదు',
  'toast.registerInvalidUser': 'నమోదు విఫలం: చెల్లని డేటా.',
  'toast.registerInvalidRole': 'నమోదు విఫలం: చెల్లని పాత్ర.',
  'toast.welcomeNewUser': 'ReRide కు స్వాగతం, {{name}}!',
  'toast.loadedVehiclesCount': '{{count}} వాహనాలు లోడ్ అయ్యాయి',
  'toast.serviceUnavailableAdmin':
    'సేవ అందుబాటులో లేదు. నిర్వాహకులు: SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY సెట్ చేసి రీడిప్లాయ్ చేయండి.',
  'toast.vehiclesLoadFailedShort': 'వాహనాలు లోడ్ కాలేదు. కనెక్షన్ చూడండి.',
  'toast.someDataFailedLoad': 'కొంత డేటా లోడ్ కాలేదు. యాప్ కొనసాగుతుంది.',
  'toast.listingsEmptyDbUnavailable':
    'లిస్టింగ్‌లు ఖాళీగా ఉన్నాయి — డేటాబేస్ అందుబాటులో లేదు. Supabase కాన్ఫిగ్ సెట్ చేయండి.',
  'toast.vehiclesLoadFailed': 'వాహనాలు లోడ్ కాలేదు. కనెక్షన్ చూసి మళ్లీ ప్రయత్నించండి.',
  'toast.dealersEmptyDbUnavailable':
    'డీలర్ వివరాలు ఖాళీ — డేటాబేస్ అందుబాటులో లేదు. Supabase కీలు సెట్ చేయండి.',
  'toast.usersLoadFailed': 'వినియోగదారులు లోడ్ కాలేదు.',
  'toast.syncedItemsCount': 'సర్వర్‌కు {{count}} అంశాలు సింక్ అయ్యాయి',
  'toast.dataSyncSuccess': 'డేటా విజయవంతంగా సింక్ అయింది',
  'toast.dataSyncPartial': 'సింక్ విఫలమైంది, యాప్ పనిచేస్తుంది',
  'toast.nowOffline': 'మీరు ఆఫ్‌లైన్. కనెక్షన్ వచ్చినప్పుడు సింక్ అవుతుంది.',
  'toast.vehicleNotFound': 'వాహనం కనుగొనబడలేదు',
  'toast.vehicleUpdatedSuccess': 'వాహనం నవీకరించబడింది',
  'toast.vehicleStatusUpdated': 'వాహన స్థితి నవీకరణ: {{status}}',
  'toast.vehicleFeaturedSuccess': 'వాహనం ఫీచర్ చేయబడింది',
  'toast.vehicleUnfeaturedSuccess': 'ఫీచర్ తీసివేయబడింది',
  'toast.vehicleUpdateFailed': 'వాహనం నవీకరణ విఫలమైంది.',
  'toast.vehicleSyncFailedDetail': 'సర్వర్ సింక్ విఫలం: {{detail}}',
  'toast.userUpdated': '{{email}} నవీకరించబడింది',
  'toast.userCreateFailedDetail': 'వినియోగదారు సృష్టి విఫలం: {{reason}}',
  'toast.userCreated': '{{name}} సృష్టించబడింది',
  'toast.planUpdateFailed': 'ప్లాన్ నవీకరణ విఫలమైంది.',
  'toast.planUpdated': '{{email}} ప్లాన్ నవీకరణ',
  'toast.userStatusToggled': '{{email}} స్థితి మార్చబడింది',
  'toast.userStatusToggleFailed': 'స్థితి మార్పు విఫలం',
  'toast.vehicleStatusUpdateFailed': 'వాహన స్థితి నవీకరణ విఫలం',
  'toast.vehicleAlreadyFeatured': 'ఇప్పటికే ఫీచర్ చేయబడింది.',
  'toast.vehicleFeaturedWithCredits': 'ఫీచర్ చేయబడింది. మిగిలిన క్రెడిట్‌లు: {{credits}}',
  'toast.featureVehicleFailed': 'ఫీచర్ చేయడం విఫలం.',
  'toast.featureStatusFailed': 'ఫీచర్ స్థితి నవీకరణ విఫలం',
  'toast.conversationNotFound': 'సంభాషణ కనుగొనబడలేదు',
  'toast.flagResolvedVehicle': 'వాహన ఫ్లాగ్ పరిష్కరించబడింది',
  'toast.flagResolvedConversation': 'సంభాషణ ఫ్లాగ్ పరిష్కరించబడింది',
  'toast.flagResolveFailedVehicle': 'వాహన ఫ్లాగ్ పరిష్కరణ విఫలం',
  'toast.flagResolveFailedConversation': 'సంభాషణ ఫ్లాగ్ పరిష్కరణ విఫలం',
  'toast.settingsUpdated': 'ప్లాట్‌ఫారమ్ సెట్టింగ్‌లు నవీకరించబడ్డాయి',
  'toast.broadcastSent': 'అందరికీ ప్రసారం పంపబడింది',
  'toast.exportUsersSuccess': '{{count}} వినియోగదారులు ఎగుమతి సఫలం',
  'toast.exportFailed': 'ఎగుమతి విఫలమైంది.',
  'toast.importUsersSuccess': '{{count}} వినియోగదారులు దిగుమతి సఫలం',
  'toast.importUsersPartialWarning': '{{count}} వినియోగదారులు దిగుమతి విఫలం',
  'toast.exportVehiclesSuccess': '{{count}} వాహనాలు ఎగుమతి సఫలం',
  'toast.importVehiclesSuccess': '{{count}} వాహనాలు దిగుమతి సఫలం',
  'toast.importVehiclesPartialWarning': '{{count}} వాహనాలు దిగుమతి విఫలం',
  'toast.exportSalesSuccess': '{{count}} అమ్మకపు రికార్డులు ఎగుమతి',
  'toast.vehicleDataUpdateFailed': 'వాహన డేటా నవీకరణ విఫలం.',
  'toast.vehicleDataUpdated': 'వాహన డేటా నవీకరించబడింది',
  'toast.verificationToggled': '{{email}} ధృవీకరణ స్థితి మార్చబడింది',
  'toast.supportTicketUpdated': 'సపోర్ట్ టికెట్ నవీకరణ',
  'toast.supportTicketUpdateFailed': 'టికెట్ నవీకరణ విఫలం',
  'toast.faqAdded': 'FAQ జోడించబడింది',
  'toast.faqAddFailed': 'FAQ జోడింపు విఫలం.',
  'toast.faqUpdated': 'FAQ నవీకరణ',
  'toast.faqUpdateFailed': 'FAQ నవీకరణ విఫలం',
  'toast.faqDeleted': 'FAQ తొలగించబడింది',
  'toast.faqDeleteFailed': 'FAQ తొలగింపు విఫలం',
  'toast.certificationApproved': 'ప్రమాణీకరణ ఆమోదించబడింది',
  'toast.certificationRejected': 'ప్రమాణీకరణ తిరస్కరించబడింది',
  'toast.certificationUpdateFailed': 'ప్రమాణీకరణ నవీకరణ విఫలం',
  'toast.ratingAdded': 'రేటింగ్ జోడించబడింది',
  'toast.sellerRatingAdded': 'విక్రేత రేటింగ్ జోడించబడింది',
  'toast.loginRequiredMessages': 'సందేశాలు పంపడానికి లాగిన్ అవ్వండి.',
  'toast.conversationNotFoundRefresh': 'సంభాషణ లేదు. రిఫ్రెష్ చేయండి.',
  'toast.failedSendMessageConnection': 'సందేశం పంపడం విఫలం. కనెక్షన్ చూడండి.',
  'toast.failedSendMessageGeneric': 'సందేశం పంపడం విఫలం.',
  'toast.contentFlagged': 'సమీక్షకు ఫ్లాగ్ చేయబడింది{{reasonSuffix}}',
  'toast.passwordUpdatedSuccess': 'పాస్‌వర్డ్ నవీకరణ సఫలం!',
  'toast.profileUpdatedSuccess': 'ప్రొఫైల్ నవీకరణ సఫలం!',
  'toast.passwordUpdateFailedReason': 'పాస్‌వర్డ్ విఫలం: {{reason}}',
  'toast.profileUpdateFailedReason': 'ప్రొఫైల్ విఫలం: {{reason}}',
  'toast.passwordUpdateFailedServer': 'పాస్‌వర్డ్: సర్వర్ లోపం.',
  'toast.profileUpdateFailedServer': 'ప్రొఫైల్: సర్వర్ లోపం.',
  'toast.passwordUpdateFailedSupabase': 'పాస్‌వర్డ్: Supabase లోపం.',
  'toast.profileUpdateFailedSupabase': 'ప్రొఫైల్: Supabase లోపం.',
  'toast.passwordUpdateFailedNetwork': 'పాస్‌వర్డ్: నెట్‌వర్క్ లోపం.',
  'toast.profileUpdateFailedNetwork': 'ప్రొఫైల్: నెట్‌వర్క్ లోపం.',
  'toast.passwordUpdateFailedNotFound': 'పాస్‌వర్డ్: API కనుగొనబడలేదు.',
  'toast.profileUpdateFailedNotFound': 'ప్రొఫైల్: API కనుగొనబడలేదు.',
  'toast.updateInvalidData': 'నవీకరణ విఫలం: చెల్లని డేటా - {{detail}}',
  'toast.passwordUpdateFailedServerRetry': 'పాస్‌వర్డ్: సర్వర్ లోపం.',
  'toast.profileUpdateFailedServerRetry': 'ప్రొఫైల్: సర్వర్ లోపం.',
  'toast.passwordUpdateFailedDisplay': 'పాస్‌వర్డ్ విఫలం: {{error}}',
  'toast.profileUpdateFailedDisplay': 'ప్రొఫైల్ విఫలం: {{error}}',
  'toast.passwordUpdateFailedCheckLogs': 'పాస్‌వర్డ్ విఫలం. లాగ్‌లు చూడండి.',
  'toast.profileUpdateFailedTryAgain': 'ప్రొఫైల్ విఫలం. మళ్లీ ప్రయత్నించండి.',
  'toast.userDeletedSuccess': 'వినియోగదారు తొలగించబడింది',
  'toast.vehicleDeletedSuccess': 'వాహనం తొలగించబడింది',
  'toast.deleteVehicleFailed': 'వాహనం తొలగింపు విఫలం',
  'toast.deleteVehicleFailedRetry': 'వాహనం తొలగింపు విఫలం.',
  'toast.offerAccepted': 'ఆఫర్ ఆమోదించబడింది',
  'toast.offerRejected': 'ఆఫర్ తిరస్కరించబడింది',
  'toast.offerCountered': 'కౌంటర్ ఆఫర్ పంపబడింది',
  'toast.unknownError': 'తెలియని లోపం',
  'vehicle.share.copyLink': 'లింక్ కాపీ చేయి',
  'vehicle.share.copied': 'కాపీ అయింది!',
  'vehicle.share.failed': 'విఫలం!',
  'vehicle.detail.photosTap': '{{count}} ఫోటోలు • చూడటానికి ట్యాప్ చేయండి',
};

export const toastTa: Record<string, string> = {
  'errors.network': 'சர்வருடன் இணைக்க முடியவில்லை. இணையத்தைச் சரிபார்க்கவும்.',
  'errors.timeout': 'கோரிக்கை நேரம் முடிந்தது. மீண்டும் முயலவும்.',
  'errors.permission': 'இச்செயலுக்கு அனுமதி இல்லை.',
  'toast.loadingVehicles': 'வாகனங்கள் ஏற்றப்படுகின்றன...',
  'toast.loggedOut': 'நீங்கள் வெளியேறினீர்கள்.',
  'toast.loginInvalidUser': 'உள்நுழைவு தோல்வி: தவறான பயனர் தரவு.',
  'toast.loginInvalidRole': 'உள்நுழைவு தோல்வி: தவறான பங்கு.',
  'toast.welcomeBack': 'மீண்டும் வரவேற்கிறோம், {{name}}!',
  'toast.googleSignInFailed': 'Google உள்நுழைவு முடியவில்லை',
  'toast.registerInvalidUser': 'பதிவு தோல்வி: தவறான தரவு.',
  'toast.registerInvalidRole': 'பதிவு தோல்வி: தவறான பங்கு.',
  'toast.welcomeNewUser': 'ReRide க்கு வரவேற்கிறோம், {{name}}!',
  'toast.loadedVehiclesCount': '{{count}} வாகனங்கள் ஏற்றப்பட்டன',
  'toast.serviceUnavailableAdmin':
    'சேவை இல்லை. நிர்வாகிகள்: SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY அமைத்து மீண்டும் வெளியிடவும்.',
  'toast.vehiclesLoadFailedShort': 'வாகனங்கள் ஏற்ற முடியவில்லை. இணைப்பைச் சரிபார்க்கவும்.',
  'toast.someDataFailedLoad': 'சில தரவு ஏற்றப்படவில்லை. பயன்பாடு தொடரும்.',
  'toast.listingsEmptyDbUnavailable':
    'பட்டியல்கள் காலி — தரவுத்தளம் இல்லை. Supabase கட்டமைப்பை அமைக்கவும்.',
  'toast.vehiclesLoadFailed': 'வாகனங்கள் ஏற்ற முடியவில்லை. இணைப்பைச் சரிபார்த்து முயலவும்.',
  'toast.dealersEmptyDbUnavailable':
    'டீலர் விவரங்கள் காலி — தரவுத்தளம் இல்லை. Supabase விசைகளை அமைக்கவும்.',
  'toast.usersLoadFailed': 'பயனர்களை ஏற்ற முடியவில்லை.',
  'toast.syncedItemsCount': 'சர்வருக்கு {{count}} உருப்படிகள் ஒத்திசைக்கப்பட்டன',
  'toast.dataSyncSuccess': 'தரவு வெற்றிகரமாக ஒத்திசைக்கப்பட்டது',
  'toast.dataSyncPartial': 'ஒத்திசைவு தோல்வி, பயன்பாடு இயங்கும்',
  'toast.nowOffline': 'நீங்கள் ஆஃப்லைன். இணைப்பு திரும்பும்போது ஒத்திசைக்கும்.',
  'toast.vehicleNotFound': 'வாகனம் கிடைக்கவில்லை',
  'toast.vehicleUpdatedSuccess': 'வாகனம் புதுப்பிக்கப்பட்டது',
  'toast.vehicleStatusUpdated': 'வாகன நிலை புதுப்பிப்பு: {{status}}',
  'toast.vehicleFeaturedSuccess': 'வாகனம் சிறப்பிடப்பட்டது',
  'toast.vehicleUnfeaturedSuccess': 'சிறப்பு நீக்கப்பட்டது',
  'toast.vehicleUpdateFailed': 'வாகன புதுப்பித்தல் தோல்வி.',
  'toast.vehicleSyncFailedDetail': 'சர்வர் ஒத்திசைவு தோல்வி: {{detail}}',
  'toast.userUpdated': '{{email}} புதுப்பிக்கப்பட்டது',
  'toast.userCreateFailedDetail': 'பயனர் உருவாக்கம் தோல்வி: {{reason}}',
  'toast.userCreated': '{{name}} உருவாக்கப்பட்டார்',
  'toast.planUpdateFailed': 'திட்ட புதுப்பித்தல் தோல்வி.',
  'toast.planUpdated': '{{email}} திட்டம் புதுப்பிக்கப்பட்டது',
  'toast.userStatusToggled': '{{email}} நிலை மாற்றப்பட்டது',
  'toast.userStatusToggleFailed': 'நிலை மாற்றம் தோல்வி',
  'toast.vehicleStatusUpdateFailed': 'வாகன நிலை புதுப்பித்தல் தோல்வி',
  'toast.vehicleAlreadyFeatured': 'ஏற்கனவே சிறப்பிடப்பட்டது.',
  'toast.vehicleFeaturedWithCredits': 'சிறப்பிடப்பட்டது. மீதமுள்ள கிரெடிட்: {{credits}}',
  'toast.featureVehicleFailed': 'சிறப்பிடுதல் தோல்வி.',
  'toast.featureStatusFailed': 'சிறப்பு நிலை புதுப்பித்தல் தோல்வி',
  'toast.conversationNotFound': 'உரையாடல் கிடைக்கவில்லை',
  'toast.flagResolvedVehicle': 'வாகன கொடி தீர்க்கப்பட்டது',
  'toast.flagResolvedConversation': 'உரையாடல் கொடி தீர்க்கப்பட்டது',
  'toast.flagResolveFailedVehicle': 'வாகன கொடி தீர்த்தல் தோல்வி',
  'toast.flagResolveFailedConversation': 'உரையாடல் கொடி தீர்த்தல் தோல்வி',
  'toast.settingsUpdated': 'தள அமைப்புகள் புதுப்பிக்கப்பட்டன',
  'toast.broadcastSent': 'அனைவருக்கும் அறிவிப்பு அனுப்பப்பட்டது',
  'toast.exportUsersSuccess': '{{count}} பயனர்கள் ஏற்றுமதி வெற்றி',
  'toast.exportFailed': 'ஏற்றுமதி தோல்வி.',
  'toast.importUsersSuccess': '{{count}} பயனர்கள் இறக்குமதி வெற்றி',
  'toast.importUsersPartialWarning': '{{count}} பயனர்கள் இறக்குமதி தோல்வி',
  'toast.exportVehiclesSuccess': '{{count}} வாகனங்கள் ஏற்றுமதி வெற்றி',
  'toast.importVehiclesSuccess': '{{count}} வாகனங்கள் இறக்குமதி வெற்றி',
  'toast.importVehiclesPartialWarning': '{{count}} வாகனங்கள் இறக்குமதி தோல்வி',
  'toast.exportSalesSuccess': '{{count}} விற்பனை பதிவுகள் ஏற்றுமதி',
  'toast.vehicleDataUpdateFailed': 'வாகன தரவு புதுப்பித்தல் தோல்வி.',
  'toast.vehicleDataUpdated': 'வாகன தரவு புதுப்பிக்கப்பட்டது',
  'toast.verificationToggled': '{{email}} சரிபார்ப்பு நிலை மாற்றப்பட்டது',
  'toast.supportTicketUpdated': 'ஆதரவு டிக்கெட் புதுப்பிக்கப்பட்டது',
  'toast.supportTicketUpdateFailed': 'டிக்கெட் புதுப்பித்தல் தோல்வி',
  'toast.faqAdded': 'FAQ சேர்க்கப்பட்டது',
  'toast.faqAddFailed': 'FAQ சேர்ப்பு தோல்வி.',
  'toast.faqUpdated': 'FAQ புதுப்பிக்கப்பட்டது',
  'toast.faqUpdateFailed': 'FAQ புதுப்பித்தல் தோல்வி',
  'toast.faqDeleted': 'FAQ நீக்கப்பட்டது',
  'toast.faqDeleteFailed': 'FAQ நீக்கம் தோல்வி',
  'toast.certificationApproved': 'சான்றிதழ் அங்கீகரிக்கப்பட்டது',
  'toast.certificationRejected': 'சான்றிதழ் நிராகரிக்கப்பட்டது',
  'toast.certificationUpdateFailed': 'சான்றிதழ் புதுப்பித்தல் தோல்வி',
  'toast.ratingAdded': 'மதிப்பீடு சேர்க்கப்பட்டது',
  'toast.sellerRatingAdded': 'விற்பனையாளர் மதிப்பீடு சேர்க்கப்பட்டது',
  'toast.loginRequiredMessages': 'செய்திகளுக்கு உள்நுழையவும்.',
  'toast.conversationNotFoundRefresh': 'உரையாடல் இல்லை. புதுப்பிக்கவும்.',
  'toast.failedSendMessageConnection': 'செய்தி அனுப்புதல் தோல்வி. இணைப்பைச் சரிபார்க்கவும்.',
  'toast.failedSendMessageGeneric': 'செய்தி அனுப்புதல் தோல்வி.',
  'toast.contentFlagged': 'மதிப்பாய்வுக்கு குறிக்கப்பட்டது{{reasonSuffix}}',
  'toast.passwordUpdatedSuccess': 'கடவுச்சொல் புதுப்பிக்கப்பட்டது!',
  'toast.profileUpdatedSuccess': 'சுயவிவரம் புதுப்பிக்கப்பட்டது!',
  'toast.passwordUpdateFailedReason': 'கடவுச்சொல் தோல்வி: {{reason}}',
  'toast.profileUpdateFailedReason': 'சுயவிவரம் தோல்வி: {{reason}}',
  'toast.passwordUpdateFailedServer': 'கடவுச்சொல்: சர்வர் பிழை.',
  'toast.profileUpdateFailedServer': 'சுயவிவரம்: சர்வர் பிழை.',
  'toast.passwordUpdateFailedSupabase': 'கடவுச்சொல்: Supabase பிழை.',
  'toast.profileUpdateFailedSupabase': 'சுயவிவரம்: Supabase பிழை.',
  'toast.passwordUpdateFailedNetwork': 'கடவுச்சொல்: நெட்வொர்க் பிழை.',
  'toast.profileUpdateFailedNetwork': 'சுயவிவரம்: நெட்வொர்க் பிழை.',
  'toast.passwordUpdateFailedNotFound': 'கடவுச்சொல்: API கிடைக்கவில்லை.',
  'toast.profileUpdateFailedNotFound': 'சுயவிவரம்: API கிடைக்கவில்லை.',
  'toast.updateInvalidData': 'புதுப்பித்தல் தோல்வி: தவறான தரவு - {{detail}}',
  'toast.passwordUpdateFailedServerRetry': 'கடவுச்சொல்: சர்வர் பிழை.',
  'toast.profileUpdateFailedServerRetry': 'சுயவிவரம்: சர்வர் பிழை.',
  'toast.passwordUpdateFailedDisplay': 'கடவுச்சொல் தோல்வி: {{error}}',
  'toast.profileUpdateFailedDisplay': 'சுயவிவரம் தோல்வி: {{error}}',
  'toast.passwordUpdateFailedCheckLogs': 'கடவுச்சொல் தோல்வி. பதிவுகளைப் பார்க்கவும்.',
  'toast.profileUpdateFailedTryAgain': 'சுயவிவரம் தோல்வி. மீண்டும் முயலவும்.',
  'toast.userDeletedSuccess': 'பயனர் நீக்கப்பட்டார்',
  'toast.vehicleDeletedSuccess': 'வாகனம் நீக்கப்பட்டது',
  'toast.deleteVehicleFailed': 'வாகன நீக்கம் தோல்வி',
  'toast.deleteVehicleFailedRetry': 'வாகன நீக்கம் தோல்வி.',
  'toast.offerAccepted': 'சலுகை ஏற்கப்பட்டது',
  'toast.offerRejected': 'சலுகை நிராகரிக்கப்பட்டது',
  'toast.offerCountered': 'எதிர்ச்சலுகை அனுப்பப்பட்டது',
  'toast.unknownError': 'தெரியாத பிழை',
  'vehicle.share.copyLink': 'இணைப்பை நகலெடு',
  'vehicle.share.copied': 'நகலெடுக்கப்பட்டது!',
  'vehicle.share.failed': 'தோல்வி!',
  'vehicle.detail.photosTap': '{{count}} புகைப்படங்கள் • பார்க்க தட்டவும்',
};
